#!/bin/sh
echo 1 > /sys/module/ov5645_camera_mipi_v2/parameters/ov5645_af
rm trackp/*
killall gst-launch-1.0
sleep 1
exec gst-launch-1.0 -v \
v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 \
! tee name=t \
t.  \
! queue max-size-buffers=1 leaky=downstream \
! videoconvert ! jpegenc ! multifilesink location=trackp/frame%04d.jpg \
t. \
! queue max-size-buffers=1 leaky=downstream \
!  videoconvert \
! x264enc speed_preset=ultrafast tune=zerolatency threads=1 key_int_max=30 bitrate=1024 aud=False \
! video/x-h264,profile=baseline\
! h264parse \
! rtph264pay mtu=1280 \
! "application/x-rtp,payload=(int)96,ssrc=(uint)555555" \
! udpsink host=127.0.0.1 port=$1
#v4l2src device=/dev/video0 ! video/x-raw,framerate=30/1,width=640,height=480,format=YUY2 ! videoconvert !   x264enc tune=zerolatency bitrate=768 speed-preset=ultrafast aud=False key-int-max=5 \
#! video/x-h264,profile=baseline ! h264parse ! rtph264pay config-interval=20 mtu=1208 ! "application/x-rtp, payload=(int)96, ssrc=(uint)555555" !  udpsink host=127.0.0.1 port=${1}
