#!/bin/sh
echo 1 > /sys/module/ov5645_camera_mipi_v2/parameters/ov5645_af
if [ -e webcam/gstrelay/gstbin ]
then 
   killall gstbin
   exec webcam/gstrelay/gstbin ${1}
else
   killall gst-launch-1.0
   echo "sending to " ${1}
   exec gst-launch-1.0 \
v4l2src device=/dev/video0 ! video/x-raw,framerate=30/1,width=640,height=480,format=YUY2 ! videoconvert !   x264enc tune=zerolatency bitrate=768 speed-preset=ultrafast aud=False key-int-max=5 \
! video/x-h264,profile=baseline ! h264parse ! rtph264pay config-interval=20 mtu=1208 ! "application/x-rtp, payload=(int)96, ssrc=(uint)555555" !  udpsink host=127.0.0.1 port=${1} 
fi

