#!/bin/sh
killall gst-launch-1.0
   echo "sending to " ${1}
   exec gst-launch-1.0 \
videotestsrc ! video/x-raw,framerate=30/1,width=640,height=480,format=YUY2 ! videoconvert !   vp8enc threads=3 target-bitrate=1024000 keyframe-max-dist=30 \
! video/x-vp8! rtpvp8pay mtu=1208 ! "application/x-rtp, payload=(int)96, ssrc=(uint)555555" !  udpsink host=127.0.0.1 port=${1}

